name: test deployment
on: [push]
jobs:  
  deploy:    
    runs-on: ubuntu-latest
    permissions: read-all | write-all
    steps:
      - uses: actions/checkout@master
      - name: deploy website to example.com
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: root
          PASWORD:  ${{secrets.PASSWORD}}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.KEY }}
        with:
          source: "dest"
          target: "/var/www/html/testcicd/test"
          strip_components: 1
